dataset:
  meta_svs: !!str meta/IBD_PROJECT/svs_meta.pickle
  meta_all: !!str meta/ibd_project_meta.pickle
  outcome: !!str "Dx (U=UC, C=Cr, I=Ind)"
  outcome_type: !!str classification
  study: !!str ibd_project
  is_cancer: !!bool False
  disease: !!str IBD_PROJECT

patch:
  num_patches: !!int 75
  magnification: !!int 20

model:
  weighted_loss: !!bool True
  
  # Weight Decays
  wd_attn: !!float 1e-3
  wd_fuse: !!float 1e-3
  wd_loss: !!float 1e-3
  wd_pred: !!float 1e-2
  
  # Learning Rates
  lr_attn: !!float 5e-6
  lr_fuse: !!float 5e-6
  lr_loss: !!float 5e-6
  lr_pred: !!float 5e-4

  accumulation_steps: !!int 2
  dropout: !!float 0.3
  batch_size: !!int 4
  override_logs: !!bool True
  sample_patient: !!bool True