dataset:
  meta_svs: !!str meta/IBD_PROJECT/svs_meta.pickle
  meta_all: !!str meta/ibd_project_meta.pickle

  # meta_svs: !!str meta/vis_ibd_project_locs-split.pickle
  # meta_all: !!str meta/vis_ibd_project_meta-split.pickle

  outcome: !!str Diagnosis
  outcome_type: !!str classification
  study: !!str ibd_project
  is_cancer: !!bool False
  disease: !!str IBD_PROJECT
  timestr_model: !!str 2023_5_30

patch:
  num_patches: !!int 150
  magnification: !!float 20

model:
  weighted_loss: !!bool True
  
  # Weight Decays
  wd_attn: !!float 1e-3
  wd_fuse: !!float 1e-3
  wd_loss: !!float 1e-3
  wd_pred: !!float 0.002
  
  # Learning Rates
  lr_attn: !!float 1e-5
  lr_fuse: !!float 1e-5
  lr_loss: !!float 1e-5
  lr_pred: !!float 7e-5

  accumulation_steps: !!int 2
  dropout: !!float 0.05
  batch_size: !!int 8
  override_logs: !!bool True
  sample_patient: !!bool True